POST http://localhost:8800/register/ HTTP/1.1
content-type: application/json

{
    "username": "test",
    "email": "test@gmail.com",
    "password": "12345"
}

###

POST http://localhost:8800/login/ HTTP/1.1
content-type: application/json

{
    "username": "rurs",
    "password": "12345"
}

###

http://localhost:8800/stats

